railway_cities_BG = ['София', 'Варна', 'Бургас', 'Пловдив', 'Русе', 'Горна оряховица', 'Стара загова', 'Плевен',
                     'Айтос', 'Асеновград', 'Батановци', 'Белово', 'Белозем', 'Белослав', 'Благоеврад',
                     'Бойчиновци',
                     'Брусарци', 'Бяла', 'Велико Търново', 'Велинград', 'Видин', 'Враца', 'Габрово', 'Даскалово',
                     'Две могили', 'Димитровград', 'Добрич', 'Дряново', 'Дупница', 'Дългопол', 'Елин Пелин',
                     'Земен',
                     'Златица', 'Зверино', 'Ихтиман', 'Казанлък', 'Карлово', 'Карнобат', 'Каспичан', 'Криводол',
                     'Крумово', 'Кюстендил', 'Кърджали', 'Лакатник', 'Левски', 'Лом', 'Ловеч', 'Мездра', 'Метал',
                     'Монтана', 'Нова Загора', 'Пазарджик', 'Павликени', 'Перник', 'Перник Разпред.', 'Пертич',
                     'Пирдоп', 'Попово', 'Попски тръмбеш', 'Провадия', 'Първомай', 'Радомир', 'Роман', 'Разград',
                     'Самуил', 'Сандански', 'Свиленград', 'Свищов', 'Своге', 'Септември', 'Силистра', 'Сливен',
                     'Сливница', 'Стамболийски', 'Стралджа', 'Стражица', 'Твърдица', 'Трявна', 'Тулово',
                     'Търговище',
                     'Филипово', 'Хисар', 'Церово', 'Червен бряг', 'Чирпан', 'Шумен', 'Ямбол']

railway_cities_EN = ['Sofia', 'Varna', 'Burgas', 'Plovdiv', 'Ruse', 'Gorna Oryakhovitsa', 'Stara Zagora', 'Pleven',
                     'Aytos', 'Asenovgrad', 'Batanovtsi', 'Belovo', 'Belozem', 'Beloslav', 'Blagoevgrad',
                     'Boychinovtsi',
                     'Brusartsi', 'Bqla', 'Veliko Tarnovo', 'Velingrad', 'Vidin', 'Vratsa', 'Gabrovo', 'Daskalovo',
                     'Dve mogili', 'Dimitrovgrad', 'Dobrich', 'Drqnovo', 'Dupnitsa', 'Dulgopol', 'Elin Pelin',
                     'Zemen',
                     'Zlatitsa', 'Zverino', 'Ihtiman', 'Kazanlak', 'Karlovo', 'Karnobat', 'Kaspichan', 'Krivodol',
                     'Krumovo', 'Kyustendil', 'Kardzhali', 'Lakatnik', 'Levski', 'Lom', 'Lovech', 'Mezdra', 'Metal',
                     'Montana', 'Nova Zagora', 'Pazardzhik', 'Pavlikeni', 'Pernik', 'Pernik razpred.', 'Petrich',
                     'Pirdop', 'Popovo', 'Polski Trambesh', 'Provadia', 'Parvomay', 'Radomir', 'Roman', 'Razgrad',
                     'Samuil', 'Sandandski', 'Svilengrad', 'Svishtov', 'Svoge', 'Septemvri', 'Silistra', 'Sliven',
                     'Slivnitsa', 'Stamboliyski', 'Straldzha', 'Strazhitsa', 'Tvarditsa', 'Tryavna', 'Tulovo',
                     'Targovishte',
                     'Filipovo', 'Hisar', 'Tserovo', 'Cherven bryag', 'Chirpan', 'Shumen', 'Yambol']
